/* Catálogo curado desde las tiendas oficiales. Las fotos son enlaces remotos; precios/tallas pueden cambiar. */
window.CLOTHES_PRODUCTS = [
  { id: 'savage-tee-white', name: 'Camiseta blanca gráfica', brand: 'Savage', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Casual', 'Vintage'], price: 89000, color: 'Blanco', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/Savage/savage_camiseta_blanca_1.jpg', logo: '../Imagenes/Marcas/Savage/savage_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'savage-hoodie', name: 'Hoodie gráfico', brand: 'Savage', audience: 'unisex', category: 'Hoodies', styles: ['Streetwear', 'Y2K', 'Techwear'], price: 189000, color: 'Diseño de muestra', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/Savage/savage_hoodie_1.jpg', logo: '../Imagenes/Marcas/Savage/savage_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'true-hoodie', name: 'Hoodie esencial', brand: 'True', audience: 'unisex', category: 'Hoodies', styles: ['Streetwear', 'Minimalista'], price: 179000, color: 'Diseño de muestra', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/True/true_hoodie_1.jpg', logo: '../Imagenes/Marcas/True/true_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'undergold-hoodie', name: 'Hoodie urbano', brand: 'Undergold', audience: 'unisex', category: 'Hoodies', styles: ['Streetwear', 'Techwear'], price: 199000, color: 'Diseño de muestra', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/Undergold/undergold_hoodie_1.jpg', logo: '../Imagenes/Marcas/Undergold/undergold_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'undergold-trouser-black', name: 'Pantalón negro', brand: 'Undergold', audience: 'unisex', category: 'Pantalones', styles: ['Streetwear', 'Minimalista', 'Old Money', 'Formal', 'Vintage'], price: 169000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/Undergold/undergold_pantalon_negro_1.jpg', logo: '../Imagenes/Marcas/Undergold/undergold_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'weedgreen-hoodie', name: 'Hoodie relaxed', brand: 'Weedgreen', audience: 'unisex', category: 'Hoodies', styles: ['Streetwear', 'Casual', 'Vintage'], price: 185000, color: 'Diseño de muestra', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/Weedgreen/weedgreen_hoodie_1.jpg', logo: '../Imagenes/Marcas/Weedgreen/weedgreen_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'buds-bermuda-denim', name: 'Bermuda Denim Baggy Azul', brand: 'Buds', audience: 'hombre', category: 'Pantalones', styles: ['Streetwear', 'Casual'], price: 150000, color: 'Azul', sizes: ['30'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/bermudaazul.png?v=1781130253', logo: '', officialUrl: 'https://www.buds.com.co/products/bermuda-denim-baggy-hombre-azul-buds', description: 'Bermuda denim baggy azul. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-jean-flare', name: 'Jean Denim Flare Gris Claro', brand: 'Buds', audience: 'hombre', category: 'Pantalones', styles: ['Streetwear', 'Vintage'], price: 195000, color: 'Gris', sizes: ['30'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/JeanFlare1.png?v=1788378749', logo: '', officialUrl: 'https://www.buds.com.co/products/jean-denim-flare-hombre-gris-claro-cortes-buds', description: 'Jean denim flare gris claro con cortes. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-cargo-chocolate', name: 'Pantalón Cargo Bota Recta Chocolate', brand: 'Buds', audience: 'hombre', category: 'Pantalones', styles: ['Streetwear', 'Casual'], price: 195000, color: 'Café', sizes: ['30'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/cargochocolate.png?v=1789509393', logo: '', officialUrl: 'https://www.buds.com.co/products/pantalon-cargo-bota-recta-chocolate-buds', description: 'Pantalón cargo de bota recta color chocolate. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-hoodie-destroyed', name: 'Buzo Hoodie Destroyed Negro', brand: 'Buds', audience: 'hombre', category: 'Hoodies', styles: ['Streetwear', 'Techwear'], price: 195000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/buzonegro.png?v=1789096567', logo: '', officialUrl: 'https://www.buds.com.co/products/buzo-hoodie-hombre-destroyed-negro-tela-alto-gramaje-400g', description: 'Hoodie destroyed negro, tela de alto gramaje. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-tank-rib', name: 'Tank Top Slim Rib Negro', brand: 'Buds', audience: 'hombre', category: 'Camisetas', styles: ['Streetwear', 'Minimalista'], price: 90000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/CamisillaRib91.png?v=1788377389', logo: '', officialUrl: 'https://www.buds.com.co/products/tank-top-slim-rib-hombre-negra-buds', description: 'Tank top slim rib para hombre. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-crop-top', name: 'Crop Top Oversize Negro', brand: 'Buds', audience: 'mujer', category: 'Camisetas', styles: ['Streetwear', 'Y2K'], price: 95000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/CropTop16.jpg?v=1788368809', logo: '', officialUrl: 'https://www.buds.com.co/products/crop-top-oversize-mujer-negro-buds', description: 'Crop top oversize negro. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'zipre-madre-tierra', name: 'Camiseta Ecológica Madre Tierra (215 g)', brand: 'ZIPRE', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Casual'], price: 89999, color: 'Diseño estampado', sizes: ['S', 'M', 'L', 'XL'], image: 'https://zipre.co/wp-content/uploads/2026/07/camiseta-6.webp', logo: '', officialUrl: 'https://zipre.co/camiseta-ecologica-madre-tierra-215g-zipre/', description: 'Diseño original elaborado mediante moda circular en Bogotá. Precio observado en la tienda oficial; verifica el valor vigente.' },
  { id: 'zipre-el-dorado', name: 'Camiseta Sostenible El Dorado (215 g)', brand: 'ZIPRE', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Vintage'], price: 89999, color: 'Beige', sizes: ['S', 'M', 'L', 'XL'], image: 'https://zipre.co/wp-content/uploads/2026/07/camiseta-2.webp', logo: '', officialUrl: 'https://zipre.co/camiseta-sostenible-el-dorado-215g-zipre/', description: 'Camiseta sostenible inspirada en la cultura de El Dorado. Precio observado en la tienda oficial; verifica el valor vigente.' },
  { id: 'zipre-elemental-aire', name: 'Camiseta Sostenible Elemental Aire', brand: 'ZIPRE', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Casual'], price: 49999, color: 'Diseño estampado', sizes: ['S', 'M', 'L', 'XL'], image: 'https://zipre.co/wp-content/uploads/2025/06/CAMISETA-AIRE-e1764790769555.webp', logo: '', officialUrl: 'https://zipre.co/camiseta-sostenible-elemental-aire/', description: 'Camiseta elaborada con tela de poliéster reciclado e inspirada en leyendas colombianas. Precio observado en la tienda oficial; verifica el valor vigente.' },
  { id: 'zipre-chaqueta-colombia', name: 'Chaqueta Ecológica Colombia Doble Faz', brand: 'ZIPRE', audience: 'unisex', category: 'Chaquetas', styles: ['Streetwear', 'Vintage'], price: 329999, color: 'Amarillo / Azul', sizes: ['S', 'M', 'L', 'XL'], image: 'https://zipre.co/wp-content/uploads/2024/03/colombia-1.jpg', logo: '', officialUrl: 'https://zipre.co/chaqueta-ecologica-colombia/', description: 'Chaqueta doble faz inspirada en Colombia. Precio observado en la tienda oficial; verifica el valor vigente.' },
  { id: 'kame-the-punisher', name: 'The Punisher Oversize', brand: 'Kame.col', audience: 'hombre', category: 'Camisetas', styles: ['Streetwear', 'Casual'], price: 69900, color: 'Negro', sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'], image: 'https://pub-05df4a1debca45a2a7db9b3bc70d7f5b.r2.dev/CACHE/images/products/66/colors/Negro/6d570a5fba68491e9659d8bf2a681f58/49cbe1003df7b8640a16a9e79ad51c8e.webp', logo: '', officialUrl: 'https://www.kamecol.com/producto/the-punisher', description: 'Camiseta oversize en algodón de 250 g, confección 100% colombiana. Verifica colores, tallas y disponibilidad en la tienda oficial.' },
  { id: 'kame-gengar', name: 'Gengar Oversize', brand: 'Kame.col', audience: 'hombre', category: 'Camisetas', styles: ['Streetwear', 'Y2K'], price: 69900, color: 'Negro', sizes: ['S', 'M', 'L', 'XL', '2XL'], image: 'https://pub-05df4a1debca45a2a7db9b3bc70d7f5b.r2.dev/CACHE/images/products/48/colors/Negro/85e1666252194cef9231439824403a20/db045e17d49b695000dc9a6a8ae6f0b0.webp', logo: '', officialUrl: 'https://www.kamecol.com/producto/gengar', description: 'Camiseta oversize en algodón de 250 g. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-hoodie-woman', name: 'Buzo Hoodie Mujer Destroyed Negro', brand: 'Buds', audience: 'mujer', category: 'Hoodies', styles: ['Streetwear', 'Techwear'], price: 195000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/Buzo47.jpg?v=1789096440', logo: '', officialUrl: 'https://www.buds.com.co/products/buzo-hoodie-mujer-destroyed-negro-tela-alto-gramaje-400g', description: 'Hoodie destroyed negro para mujer. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'sinners-center-logo-red', name: 'Camiseta Center Logo roja', brand: 'SINNERS', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Casual'], price: 120000, color: 'Rojo', sizes: ['S', 'M', 'L', 'XL', 'XXL'], image: 'https://thesinnersgallery.com/cdn/shop/files/IMG_4203copia.png?v=1761788699&width=2365', logo: '', officialUrl: 'https://thesinnersgallery.com/products/sinners-logo-red-t-shirt', description: 'Camiseta roja de algodón de alto gramaje, diseñada en Medellín. Precio observado en la tienda oficial; confirma precio y disponibilidad antes de comprar.' },
  { id: 'sinners-center-logo-white', name: 'Camiseta Center Logo blanca', brand: 'SINNERS', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Minimalista'], price: 140000, color: 'Blanco', sizes: ['S', 'M', 'L', 'XL', 'XXL'], image: 'https://thesinnersgallery.com/cdn/shop/files/IMG_4183copia.png?v=1761788687&width=2394', logo: '', officialUrl: 'https://thesinnersgallery.com/products/center-logo-white-t-shirt', description: 'Camiseta blanca de algodón de alto gramaje, diseñada en Medellín. Precio observado en la tienda oficial; confirma precio y disponibilidad antes de comprar.' },
  { id: 'sinners-garments-black-hoodie', name: 'Hoodie Garments negro', brand: 'SINNERS', audience: 'unisex', category: 'Hoodies', styles: ['Streetwear', 'Techwear'], price: 370000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: 'https://thesinnersgallery.com/cdn/shop/files/IMG_7211copia.png?v=1745537111&width=2277', logo: '', officialUrl: 'https://thesinnersgallery.com/products/garments-black-hoodie', description: 'Buzo de capucha de algodón de alto gramaje, diseñado en Medellín. Precio observado en la tienda oficial; confirma precio y disponibilidad antes de comprar.' },
  { id: 'mattelsa-tee-oversize-ivory', name: 'Camiseta Oversize Marfil Ilustración', brand: 'Mattelsa', audience: 'hombre', category: 'Camisetas', styles: ['Streetwear', 'Y2K'], price: 125000, color: 'Marfil', sizes: ['S', 'M', 'L', 'XL'], image: 'https://b2cmattelsa.vtexassets.com/arquivos/ids/747151-800-auto?aspect=true&height=auto&v=639247313895930000&width=800', logo: '', officialUrl: 'https://www.mattelsa.net/camiseta-oversize-marfil-ilustracion-95030/p', description: 'Camiseta oversize de algodón con ilustración frontal. Prenda listada en la sección de hombre de Mattelsa; consulta disponibilidad y precio vigente en la tienda oficial.' },
  { id: 'mattelsa-hoodie-oversize-black-icon', name: 'Buzo Hoodie Oversize Negro Ícono', brand: 'Mattelsa', audience: 'hombre', category: 'Hoodies', styles: ['Streetwear', 'Casual'], price: 249000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: 'https://b2cmattelsa.vtexassets.com/arquivos/ids/747847-800-auto?aspect=true&height=auto&v=639252798838930000&width=800', logo: '', officialUrl: 'https://www.mattelsa.net/buzo-hoodie-oversize-negro-icono-95049/p', description: 'Hoodie oversize negro con gráfico Ícono. Consulta tallas, disponibilidad y precio vigente en la tienda oficial.' },
  { id: 'seven-men-screen-tee-white', name: 'Camiseta Screen Frontal en Algodón', brand: 'Seven Seven', audience: 'hombre', category: 'Camisetas', styles: ['Streetwear', 'Casual'], price: 59900, color: 'Blanco', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://www.sevenseven.com/dw/image/v2/BHFM_PRD/on/demandware.static/-/Sites-storefront_catalog_sevenseven/default/dwe086b4da/images/hi-res/SevenSeven/Camiseta-Para-Hombre-45098300-10215_1.jpg?sw=600&sh=720', logo: '', officialUrl: 'https://www.sevenseven.com/camiseta-screen-frontal-en-algodon/45098300.html?dwvar_45098300_color=Blanco', description: 'Camiseta masculina de algodón con screen frontal. Precio publicado en la tienda oficial; puede variar según promociones.' },
  { id: 'seven-men-rustic-shirt-ivory', name: 'Camisa Rústica Corte Recto', brand: 'Seven Seven', audience: 'hombre', category: 'Camisas', styles: ['Casual', 'Old Money'], price: 149900, color: 'Marfil', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://www.sevenseven.com/dw/image/v2/BHFM_PRD/on/demandware.static/-/Sites-storefront_catalog_sevenseven/default/dwdf68913a/images/hi-res/SevenSeven/Camisa-Para-Hombre-45017657-10453_1.jpg?sw=600&sh=720', logo: '', officialUrl: 'https://www.sevenseven.com/camisa-rustica-corte-recto/45017657.html?dwvar_45017657_color=Marfil', description: 'Camisa para hombre de corte recto y tejido rústico. Consulta disponibilidad y precio vigente en la tienda oficial.' },
  { id: 'seven-men-bomber-wine', name: 'Chaqueta Bomber Bordada Vino', brand: 'Seven Seven', audience: 'hombre', category: 'Chaquetas', styles: ['Streetwear', 'Vintage'], price: 269000, color: 'Vino', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://www.sevenseven.com/dw/image/v2/BHFM_PRD/on/demandware.static/-/Sites-storefront_catalog_sevenseven/default/dwd6e9c134/images/hi-res/SevenSeven/Chaqueta-Para-Hombre-45080535-1_1.jpg?sw=600&sh=720', logo: '', officialUrl: 'https://www.sevenseven.com/chaqueta-bomber-bordada/45080535.html?dwvar_45080535_color=Vino', description: 'Chaqueta bomber bordada para hombre, en tono vino. Consulta tallas y disponibilidad en la tienda oficial.' },
  { id: 'seven-men-jersey-screen-navy', name: 'Camiseta Jersey Screen Azul Oscuro', brand: 'Seven Seven', audience: 'hombre', category: 'Camisetas', styles: ['Streetwear', 'Casual'], price: 99900, color: 'Azul oscuro', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://www.sevenseven.com/dw/image/v2/BHFM_PRD/on/demandware.static/-/Sites-storefront_catalog_sevenseven/default/dw01707ab0/images/hi-res/SevenSeven/Camiseta-Para-Hombre-45098283-52140_1.jpg?sw=600&sh=720', logo: '', officialUrl: 'https://www.sevenseven.com/camiseta-jersey-screen/45098283.html?dwvar_45098283_color=AzulOscuro', description: 'Camiseta jersey con screen para hombre. Precio publicado en la tienda oficial; puede cambiar.' },
  { id: 'true-racing-carpenter-jeans-gray-men', name: 'Racing Carpenter Jeans Gris', brand: 'True', audience: 'hombre', category: 'Jeans', styles: ['Streetwear', 'Vintage'], price: 320000, color: 'Gris', sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'], image: 'https://trueshop.co/cdn/shop/files/Racing-Carpenter-Jeans---Gray_1_1_1200x1200.jpg?v=1770654290', logo: '../Imagenes/Marcas/True/true_logo.png', officialUrl: 'https://trueshop.co/products/racing-carpenter-jeans-gray', description: 'Jean gris estilo carpintero, tiro medio y bota ancha; la tienda lo identifica como silueta masculina.' },
  { id: 'true-racing-camo-carpenter-men', name: 'Racing Camo Carpenter Pants Verde', brand: 'True', audience: 'hombre', category: 'Pantalones', styles: ['Streetwear', 'Techwear'], price: 320000, color: 'Verde', sizes: ['L', 'XL', 'XXL'], image: 'https://trueshop.co/cdn/shop/files/Racing-Camo-Carpenter-Pants---Green_1_1_24e35652-e1ad-4100-b3b8-592359037524_1200x1200.jpg?v=1771273910', logo: '../Imagenes/Marcas/True/true_logo.png', officialUrl: 'https://trueshop.co/products/racing-camo-carpenter-pants-green', description: 'Pantalón cargo carpintero con estampado camuflado y silueta masculina. En la tienda oficial aparecen tallas L, XL y XXL disponibles al consultar.' },
  { id: 'anewcross-armour-tee-men', name: 'Armour T-Shirt in Cotton Gris', brand: 'A New Cross', audience: 'hombre', category: 'Camisetas', styles: ['Streetwear', 'Minimalista'], price: 300000, color: 'Gris', sizes: ['S', 'M', 'L', 'XL'], image: 'https://anewcross.com/cdn/shop/files/CAMISETAARMOURGRIS1_453c34e9-bd4c-44e3-87dd-b2551bd43e4b.jpg?v=1693948423&width=800', logo: '', officialUrl: 'https://anewcross.com/products/armour-t-shirt-in-cotton', description: 'Camiseta masculina Armour en algodón Pima peruano, con estructura semiajustada. Precio publicado en la colección masculina.' },
  { id: 'anewcross-ranglan-sweatshirt-men', name: 'Ranglan Sleeve Sweatshirt in Cotton', brand: 'A New Cross', audience: 'hombre', category: 'Buzos', styles: ['Streetwear', 'Casual'], price: 450000, color: 'Gris', sizes: ['S', 'M', 'L', 'XL'], image: 'https://anewcross.com/cdn/shop/files/CAMISETARANGLANMANGALARGA_1_a4d88d7c-a7f6-423a-b55e-d9fb0b8df1a4.jpg?v=1749681754&width=800', logo: '', officialUrl: 'https://anewcross.com/products/ranglan-sleeve-sweatshirt-in-cotton', description: 'Sudadera de manga raglán confeccionada en algodón. Producto incluido en la colección de hombre de A New Cross.' },
  { id: 'seven-women-wide-leg-jean-black', name: 'Jean Wide Leg con Desgaste Negro', brand: 'Seven Seven', audience: 'mujer', category: 'Jeans', styles: ['Streetwear', 'Y2K'], price: 179900, color: 'Negro', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://www.sevenseven.com/dw/image/v2/BHFM_PRD/on/demandware.static/-/Sites-storefront_catalog_sevenseven/default/dw3d88ee95/images/hi-res/SevenSeven/Jean-Para-Mujer-28168295-10_1.jpg?sw=600&sh=720', logo: '', officialUrl: 'https://www.sevenseven.com/jean-wide-leg-con-desgaste/28168295.html?dwvar_28168295_color=Negro', description: 'Jean wide leg negro con desgaste, publicado en la sección de ropa para mujer de Seven Seven.' },
  { id: 'seven-women-denim-short-dress-blue', name: 'Vestido Corto Denim Azul', brand: 'Seven Seven', audience: 'mujer', category: 'Vestidos', styles: ['Y2K', 'Casual'], price: 159900, color: 'Azul', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://www.sevenseven.com/dw/image/v2/BHFM_PRD/on/demandware.static/-/Sites-storefront_catalog_sevenseven/default/dwae1fff12/images/hi-res/SevenSeven/Vestido-Para-Mujer-28178686-5787_1.jpg?sw=600&sh=720', logo: '', officialUrl: 'https://www.sevenseven.com/vestido-corto-denim/28178686.html?dwvar_28178686_color=AzulRey', description: 'Vestido corto de denim azul, listado en la sección femenina de Seven Seven.' },
  { id: 'seven-women-biker-jacket-taupe', name: 'Chaqueta Biker Acabado PU Taupe', brand: 'Seven Seven', audience: 'mujer', category: 'Chaquetas', styles: ['Streetwear', 'Y2K'], price: 179900, color: 'Taupe', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://www.sevenseven.com/dw/image/v2/BHFM_PRD/on/demandware.static/-/Sites-storefront_catalog_sevenseven/default/dw21365372/images/hi-res/SevenSeven/Chaqueta-para-mujer-28081038-78577_1.jpg?sw=600&sh=720', logo: '', officialUrl: 'https://www.sevenseven.com/chaqueta-biker-acabado-pu/28081038.html?dwvar_28081038_color=Taupe', description: 'Chaqueta biker femenina con acabado tipo cuero PU, color taupe.' },
  { id: 'seven-women-mesh-blouse-black', name: 'Blusa Mesh con Escote Negra', brand: 'Seven Seven', audience: 'mujer', category: 'Blusas', styles: ['Streetwear', 'Y2K'], price: 79900, color: 'Negro', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://www.sevenseven.com/dw/image/v2/BHFM_PRD/on/demandware.static/-/Sites-storefront_catalog_sevenseven/default/dw89556924/images/hi-res/SevenSeven/Camiseta-Para-Mujer-28098358-10_1.jpg?sw=600&sh=720', logo: '', officialUrl: 'https://www.sevenseven.com/blusa-mesh-con-escote/28098358.html?dwvar_28098358_color=Negro', description: 'Blusa negra de mesh con escote, publicada en la sección de ropa para mujer de Seven Seven.' },
  { id: 'agua-lolita-celina-bikini-top', name: 'Top de Bikini Lolita Celina', brand: 'Agua Bendita', audience: 'mujer', category: 'Tops de bikini', styles: ['Casual', 'Y2K'], price: 350000, color: 'Multicolor', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://www.aguabendita.com.co/cdn/shop/files/Celina-Top-de-Bikini-Lolita-22323-1_1024x1024.jpg?v=1788391011', logo: '', officialUrl: 'https://www.aguabendita.com.co/products/celina-top-de-bikini-lolita-22323', description: 'Top de bikini triangular, con mostacillas hechas a mano, tiras ajustables y estampado localizado.' },
  { id: 'agua-mariel-celina-onepiece', name: 'Vestido de Baño Entero Mariel Celina', brand: 'Agua Bendita', audience: 'mujer', category: 'Traje de baño entero', styles: ['Casual', 'Y2K'], price: 450000, color: 'Multicolor', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://www.aguabendita.com.co/cdn/shop/files/Celina-Vestido-de-Bano-Entero-Mariel-22315-1_1024x1024.jpg?v=1788390734', logo: '', officialUrl: 'https://www.aguabendita.com.co/products/celina-vestido-de-bano-entero-mariel-22315', description: 'Vestido de baño reversible con escote recto, tiras ajustables y amarres laterales; tiene dos estampados.' },
  { id: 'baobab-alora-maxi-dress-ambra', name: 'Alora Maxi Dress Ambra', brand: 'Baobab', audience: 'mujer', category: 'Vestidos', styles: ['Formal', 'Vintage'], price: 500000, color: 'Naranja', sizes: ['XS', 'S', 'M', 'L'], image: 'https://baobab.com.co/cdn/shop/files/BAOBABCOMSEP2527002_f02e4dd0-403f-4cda-9d35-48c1f51a453e.webp?v=1759409222&width=800', logo: '', officialUrl: 'https://baobab.com.co/collections/knitwear/products/alora-dress-ambra', description: 'Vestido maxi tejido de punto en tono Ambra, con cuello alto, mangas removibles y cortes asimétricos.' },
  { id: 'maygel-montt-dress-steel-blue', name: 'Montt Dress Azul Acero', brand: 'Maygel Coronel', audience: 'mujer', category: 'Vestidos', styles: ['Formal', 'Vintage'], price: 1000000, color: 'Azul acero', sizes: ['PETITE', 'ONE SIZE', 'EXTENDED'], image: 'https://co.maygelcoronel.com/cdn/shop/files/VT-070MONTT.png?v=1714414196', logo: '', officialUrl: 'https://co.maygelcoronel.com/products/montt-dress', description: 'Vestido Montt azul acero con detalle de nudo en el hombro y recogido en cintura y cadera.' },
  { id: 'lobo-rosa-ciara-dress-blue', name: 'Ciara Dress', brand: 'Lobo Rosa', audience: 'mujer', category: 'Vestidos', styles: ['Vintage', 'Formal'], price: 598000, color: 'Azul', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://loborosa.com/wp-content/uploads/2024/01/1251084_Ciara-Dress_1-600x750.jpg', logo: '', officialUrl: 'https://loborosa.com/product/ciara-dress/', description: 'Vestido largo de manga corta con bolero largo en el ruedo. Consulta estampados y tallas disponibles en la tienda.' },
  { id: 'suki-body-ruby-black', name: 'Body Ruby Negro', brand: 'Suki Cohen', audience: 'mujer', category: 'Bodies', styles: ['Formal', 'Streetwear'], price: 480000, color: 'Negro', sizes: ['XS', 'S', 'M', 'L', 'XL'], image: 'https://sukicohen.com/wp-content/uploads/2026/07/body_ruby_negro_1.jpg', logo: '', officialUrl: 'https://sukicohen.com/producto/body-ink-copy/?lang=es', description: 'Body Ruby negro de la colección femenina de Suki Cohen.' }
  ,{ id: 'lowtrip-baby-tee-basic', name: 'Baby Tee Basic blanca', brand: 'Low Trip', audience: 'mujer', category: 'Camisetas', styles: ['Streetwear', 'Casual', 'Y2K'], price: 70000, color: 'Blanco con estampado negro', sizes: ['XS', 'S', 'M'], image: '../Imagenes/placeholder-prenda.svg', logo: '', officialUrl: 'https://lowtripstudios.com/products/baby-tee-basic?variant=52298610737434', description: 'Baby tee slim fit de algodón, con gráfica tipográfica frontal. Hecha en Bogotá. La marca la clasifica como exclusiva para mujer.' }
  ,{ id: 'lowtrip-knitted-double-zip-black', name: 'Knitted Double Zip negro', brand: 'Low Trip', audience: 'unisex', category: 'Suéteres', styles: ['Streetwear', 'Casual'], price: 250000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/placeholder-prenda.svg', logo: '', officialUrl: 'https://lowtripstudios.com/products/knitted-double-zip?variant=52639500861722', description: 'Suéter tejido unisex con cierre doble. Consulta tallas y disponibilidad en la tienda oficial.' }
  ,{ id: 'lowtrip-knitted-double-zip-blue', name: 'Knitted Double Zip azul', brand: 'Low Trip', audience: 'unisex', category: 'Suéteres', styles: ['Streetwear', 'Casual'], price: 250000, color: 'Azul', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/placeholder-prenda.svg', logo: '', officialUrl: 'https://lowtripstudios.com/products/knitted-double-zip-1?variant=52639504367898', description: 'Suéter tejido unisex azul con cierre doble. Consulta tallas y disponibilidad en la tienda oficial.' }
  ,{ id: 'lowtrip-long-sleeve-black', name: 'Long Sleeve Basic negra', brand: 'Low Trip', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Casual'], price: 175000, color: 'Negro', sizes: ['S', 'M', 'L'], image: '../Imagenes/placeholder-prenda.svg', logo: '', officialUrl: 'https://lowtripstudios.com/products/long-sleeve-basic?variant=52298586390810', description: 'Camiseta unisex negra de manga larga. Consulta tallas y disponibilidad en la tienda oficial.' }
  ,{ id: 'lowtrip-long-sleeve-white-signature', name: 'Long Sleeve White Signature', brand: 'Low Trip', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Casual', 'Minimalista'], price: 175000, color: 'Blanco con estampados negros', sizes: ['S', 'M', 'L'], image: '../Imagenes/placeholder-prenda.svg', logo: '', officialUrl: 'https://lowtripstudios.com/products/long-sleeve-basic-1?variant=52298600186138', description: 'Camiseta unisex blanca boxy/oversized con gráficos en mangas. Consulta tallas en la tienda oficial.' }
];

// El catálogo estático sigue funcionando cuando Supabase aún no se configura.
window.CLOTHES_PRODUCTS_READY = fetch('/api/catalog')
  .then(response => response.ok ? response.json() : null)
  .then(remoteProducts => {
    if (Array.isArray(remoteProducts) && remoteProducts.length) {
      const merged = new Map(window.CLOTHES_PRODUCTS.map(product => [product.id, product]));
      remoteProducts.forEach(product => merged.set(product.id, { ...merged.get(product.id), ...product }));
      window.CLOTHES_PRODUCTS.splice(0, window.CLOTHES_PRODUCTS.length, ...[...merged.values()].filter(product => product.active !== false));
    }
    return window.CLOTHES_PRODUCTS;
  })
  .catch(() => window.CLOTHES_PRODUCTS);

const getVisitorId = () => {
  let id = localStorage.getItem('novum.visitorId');
  if (!id) { id = crypto.randomUUID(); localStorage.setItem('novum.visitorId', id); }
  return id;
};
window.NOVUM_TRACK = (kind, productId = '') => fetch('/api/analytics', {
  method: 'POST', headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ kind, productId, visitorId: getVisitorId() }), keepalive: true
}).catch(() => {});
const reportPresence = () => window.NOVUM_TRACK('heartbeat');
reportPresence();
window.setInterval(reportPresence, 60_000);
