/* Catálogo curado desde las tiendas oficiales. Las fotos son enlaces remotos; precios/tallas pueden cambiar. */
window.CLOTHES_PRODUCTS = [
  { id: 'savage-tee-white', name: 'Camiseta blanca gráfica', brand: 'Savage', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Casual', 'Vintage'], price: 89000, color: 'Blanco', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/Savage/savage_camiseta_blanca_1.jpg', logo: '../Imagenes/Marcas/Savage/savage_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'savage-hoodie', name: 'Hoodie gráfico', brand: 'Savage', audience: 'unisex', category: 'Hoodies', styles: ['Streetwear', 'Y2K', 'Techwear'], price: 189000, color: 'Diseño de muestra', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/Savage/savage_hoodie_1.jpg', logo: '../Imagenes/Marcas/Savage/savage_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'true-hoodie', name: 'Hoodie esencial', brand: 'True', audience: 'unisex', category: 'Hoodies', styles: ['Streetwear', 'Minimalista'], price: 179000, color: 'Diseño de muestra', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/True/true_hoodie_1.jpg', logo: '../Imagenes/Marcas/True/true_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'undergold-hoodie', name: 'Hoodie urbano', brand: 'Undergold', audience: 'unisex', category: 'Hoodies', styles: ['Streetwear', 'Techwear'], price: 199000, color: 'Diseño de muestra', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/Undergold/undergold_hoodie_1.jpg', logo: '../Imagenes/Marcas/Undergold/undergold_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'undergold-trouser-black', name: 'Pantalón negro', brand: 'Undergold', audience: 'unisex', category: 'Pantalones', styles: ['Streetwear', 'Minimalista', 'Old Money', 'Formal', 'Vintage'], price: 169000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/Undergold/undergold_pantalon_negro_1.jpg', logo: '../Imagenes/Marcas/Undergold/undergold_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'weedgreen-hoodie', name: 'Hoodie relaxed', brand: 'Weedgreen', audience: 'unisex', category: 'Hoodies', styles: ['Streetwear', 'Casual', 'Vintage'], price: 185000, color: 'Diseño de muestra', sizes: ['S', 'M', 'L', 'XL'], image: '../Imagenes/Marcas/Weedgreen/weedgreen_hoodie_1.jpg', logo: '../Imagenes/Marcas/Weedgreen/weedgreen_logo.png', source: 'muestra', description: 'Prenda del catálogo que ya tenías. El precio y la disponibilidad son de referencia.' },
  { id: 'buds-bermuda-denim', name: 'Bermuda Denim Baggy Azul', brand: 'Buds', audience: 'hombre', category: 'Pantalones', styles: ['Streetwear', 'Casual'], price: 150000, color: 'Azul', sizes: ['30'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/bermudaazul.png?v=1781130253', logo: '', officialUrl: 'https://www.buds.com.co/products/bermuda-denim-baggy-hombre-azul-buds', description: 'Bermuda denim baggy azul. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-jean-flare', name: 'Jean Denim Flare Gris Claro', brand: 'Buds', audience: 'hombre', category: 'Pantalones', styles: ['Streetwear', 'Vintage'], price: 195000, color: 'Gris', sizes: ['30'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/JeanFlare1.png?v=1788378749', logo: '', officialUrl: 'https://www.buds.com.co/products/jean-denim-flare-hombre-gris-claro-cortes-buds', description: 'Jean denim flare gris claro con cortes. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-cargo-chocolate', name: 'Pantalón Cargo Bota Recta Chocolate', brand: 'Buds', audience: 'hombre', category: 'Pantalones', styles: ['Streetwear', 'Casual'], price: 195000, color: 'Café', sizes: ['30'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/cargochocolate.png?v=1789509393', logo: '', officialUrl: 'https://www.buds.com.co/products/pantalon-cargo-bota-recta-chocolate-buds', description: 'Pantalón cargo de bota recta color chocolate. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-hoodie-destroyed', name: 'Buzo Hoodie Destroyed Negro', brand: 'Buds', audience: 'hombre', category: 'Hoodies', styles: ['Streetwear', 'Techwear'], price: 195000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/buzonegro.png?v=1789096567', logo: '', officialUrl: 'https://www.buds.com.co/products/buzo-hoodie-hombre-destroyed-negro-tela-alto-gramaje-400g', description: 'Hoodie destroyed negro, tela de alto gramaje. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-tank-rib', name: 'Tank Top Slim Rib Negro', brand: 'Buds', audience: 'hombre', category: 'Camisetas', styles: ['Streetwear', 'Minimalista'], price: 90000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/CamisillaRib91.png?v=1788377389', logo: '', officialUrl: 'https://www.buds.com.co/products/tank-top-slim-rib-hombre-negra-buds', description: 'Tank top slim rib para hombre. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-crop-top', name: 'Crop Top Oversize Negro', brand: 'Buds', audience: 'mujer', category: 'Camisetas', styles: ['Streetwear', 'Y2K'], price: 95000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/CropTop16.jpg?v=1788368809', logo: '', officialUrl: 'https://www.buds.com.co/products/crop-top-oversize-mujer-negro-buds', description: 'Crop top oversize negro. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'zipre-madre-tierra', name: 'Camiseta Ecológica Madre Tierra (215 g)', brand: 'ZIPRE', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Casual'], price: 89999, color: 'Diseño estampado', sizes: ['S', 'M', 'L', 'XL'], image: 'https://zipre.co/wp-content/uploads/2026/07/camiseta-6.webp', logo: '', officialUrl: 'https://zipre.co/camiseta-ecologica-madre-tierra-215g-zipre/', description: 'Diseño original elaborado mediante moda circular en Bogotá. Precio observado en la tienda oficial; verifica el valor vigente.' },
  { id: 'zipre-el-dorado', name: 'Camiseta Sostenible El Dorado (215 g)', brand: 'ZIPRE', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Vintage'], price: 89999, color: 'Beige', sizes: ['S', 'M', 'L', 'XL'], image: 'https://zipre.co/wp-content/uploads/2026/07/camiseta-2.webp', logo: '', officialUrl: 'https://zipre.co/camiseta-sostenible-el-dorado-215g-zipre/', description: 'Camiseta sostenible inspirada en la cultura de El Dorado. Precio observado en la tienda oficial; verifica el valor vigente.' },
  { id: 'zipre-elemental-aire', name: 'Camiseta Sostenible Elemental Aire', brand: 'ZIPRE', audience: 'unisex', category: 'Camisetas', styles: ['Streetwear', 'Casual'], price: 49999, color: 'Diseño estampado', sizes: ['S', 'M', 'L', 'XL'], image: 'https://zipre.co/wp-content/uploads/2025/06/CAMISETA-AIRE-e1764790769555.webp', logo: '', officialUrl: 'https://zipre.co/camiseta-sostenible-elemental-aire/', description: 'Camiseta elaborada con tela de poliéster reciclado e inspirada en leyendas colombianas. Precio observado en la tienda oficial; verifica el valor vigente.' },
  { id: 'zipre-chaqueta-colombia', name: 'Chaqueta Ecológica Colombia Doble Faz', brand: 'ZIPRE', audience: 'unisex', category: 'Chaquetas', styles: ['Streetwear', 'Vintage'], price: 329999, color: 'Amarillo / Azul', sizes: ['S', 'M', 'L', 'XL'], image: 'https://zipre.co/wp-content/uploads/2024/03/colombia-1.jpg', logo: '', officialUrl: 'https://zipre.co/chaqueta-ecologica-colombia/', description: 'Chaqueta doble faz inspirada en Colombia. Precio observado en la tienda oficial; verifica el valor vigente.' },
  { id: 'kame-the-punisher', name: 'The Punisher Oversize', brand: 'Kame.col', audience: 'hombre', category: 'Camisetas', styles: ['Streetwear', 'Casual'], price: 69900, color: 'Negro', sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'], image: 'https://pub-05df4a1debca45a2a7db9b3bc70d7f5b.r2.dev/CACHE/images/products/66/colors/Negro/6d570a5fba68491e9659d8bf2a681f58/49cbe1003df7b8640a16a9e79ad51c8e.webp', logo: '', officialUrl: 'https://www.kamecol.com/producto/the-punisher', description: 'Camiseta oversize en algodón de 250 g, confección 100% colombiana. Verifica colores, tallas y disponibilidad en la tienda oficial.' },
  { id: 'kame-gengar', name: 'Gengar Oversize', brand: 'Kame.col', audience: 'hombre', category: 'Camisetas', styles: ['Streetwear', 'Y2K'], price: 69900, color: 'Negro', sizes: ['S', 'M', 'L', 'XL', '2XL'], image: 'https://pub-05df4a1debca45a2a7db9b3bc70d7f5b.r2.dev/CACHE/images/products/48/colors/Negro/85e1666252194cef9231439824403a20/db045e17d49b695000dc9a6a8ae6f0b0.webp', logo: '', officialUrl: 'https://www.kamecol.com/producto/gengar', description: 'Camiseta oversize en algodón de 250 g. Consulta disponibilidad y guía de tallas en la tienda oficial.' },
  { id: 'buds-hoodie-woman', name: 'Buzo Hoodie Mujer Destroyed Negro', brand: 'Buds', audience: 'mujer', category: 'Hoodies', styles: ['Streetwear', 'Techwear'], price: 195000, color: 'Negro', sizes: ['S', 'M', 'L', 'XL'], image: 'https://cdn.shopify.com/s/files/1/0673/8791/6466/files/Buzo47.jpg?v=1789096440', logo: '', officialUrl: 'https://www.buds.com.co/products/buzo-hoodie-mujer-destroyed-negro-tela-alto-gramaje-400g', description: 'Hoodie destroyed negro para mujer. Consulta disponibilidad y guía de tallas en la tienda oficial.' }
];
